version: '2'

services:
  db:
    image: postgres
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash run.sh
    volumes:
      - ./:/todo
    ports:
      - "8000:8000"
    depends_on:
      - db
